# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yield_final.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
import numpy as np
from PyQt5.QtWidgets import QLineEdit
from PyQt5.QtWidgets import QLabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 569)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 50, 471, 51))
        self.label.setObjectName("label")
        self.area_input = QtWidgets.QLineEdit(self.centralwidget)
        self.area_input.setGeometry(QtCore.QRect(670, 140, 141, 21))
        self.area_input.setObjectName("area_input")
        self.item_input = QtWidgets.QLineEdit(self.centralwidget)
        self.item_input.setGeometry(QtCore.QRect(670, 180, 141, 21))
        self.item_input.setObjectName("item_input")
        self.temperature_input = QtWidgets.QLineEdit(self.centralwidget)
        self.temperature_input.setGeometry(QtCore.QRect(670, 340, 141, 21))
        self.temperature_input.setObjectName("temperature_input")
        self.year_input = QtWidgets.QLineEdit(self.centralwidget)
        self.year_input.setGeometry(QtCore.QRect(670, 220, 141, 21))
        self.year_input.setObjectName("year_input")
        self.rainfall_input = QtWidgets.QLineEdit(self.centralwidget)
        self.rainfall_input.setGeometry(QtCore.QRect(670, 260, 141, 21))
        self.rainfall_input.setObjectName("rainfall_input")
        self.pesticides_input = QtWidgets.QLineEdit(self.centralwidget)
        self.pesticides_input.setGeometry(QtCore.QRect(670, 300, 141, 21))
        self.pesticides_input.setObjectName("pesticides_input")
        self.area = QtWidgets.QLabel(self.centralwidget)
        self.area.setGeometry(QtCore.QRect(570, 140, 81, 21))
        self.area.setObjectName("area")
        self.item = QtWidgets.QLabel(self.centralwidget)
        self.item.setGeometry(QtCore.QRect(570, 180, 51, 16))
        self.item.setObjectName("item")
        self.year = QtWidgets.QLabel(self.centralwidget)
        self.year.setGeometry(QtCore.QRect(570, 220, 51, 16))
        self.year.setObjectName("year")
        self.rainfall = QtWidgets.QLabel(self.centralwidget)
        self.rainfall.setGeometry(QtCore.QRect(570, 260, 61, 21))
        self.rainfall.setObjectName("rainfall")
        self.pesticides = QtWidgets.QLabel(self.centralwidget)
        self.pesticides.setGeometry(QtCore.QRect(570, 300, 71, 16))
        self.pesticides.setObjectName("pesticides")
        self.temperature = QtWidgets.QLabel(self.centralwidget)
        self.temperature.setGeometry(QtCore.QRect(570, 340, 81, 16))
        self.temperature.setObjectName("temperature")
        self.PREDICTION = QtWidgets.QPushButton(self.centralwidget)
        self.PREDICTION.setGeometry(QtCore.QRect(630, 380, 151, 21))
        self.PREDICTION.setObjectName("PREDICTION")
        self.predicted_yield = QtWidgets.QLabel(self.centralwidget)
        self.predicted_yield.setGeometry(QtCore.QRect(560, 430, 111, 21))
        self.predicted_yield.setObjectName("predicted_yield")
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(700, 420, 131, 31))
        self.output.setFrameShape(QtWidgets.QFrame.Box)
        self.output.setText("")
        self.output.setObjectName("output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1013, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.PREDICTION.clicked.connect(self.prediction)



    def prediction(self):
        
        dataset = pd.read_csv('NEW_YIELD.csv')
        print(dataset)

        x = dataset.iloc[:,:-1].values
        y = dataset.iloc[:,-1].values

        print("SPLITTING DATASET TRAIN AND TESt")
        from sklearn.model_selection import train_test_split # for splitting dataset
        x_train,x_test,y_train,y_test = train_test_split(x ,y, test_size = 0.20 ,random_state = 0)
        #printing the spliited dataset
        print("x_train=",x_train)
        print("x_test=",x_test)
        print("y_train=",y_train)
        print("y_test=",y_test)

        print(" K NEIGBOR CLASSIFICATION")
        from sklearn.svm import SVR
        regressor = SVR(kernel='linear')
        regressor.fit(X_train,Y_train)
        print("TRAINING ACCURACY")
        print('KNeighborsClassifier Training Accuracy:', regressor.score(x_train, y_train))

        a1 = self.area_input.text()
        a2 = self.item_input.text()
        a3 = self.year_input.text()
        a4 = self.rainfall_input.text()
        a5 = self.pesticides_input.text()
        a6 = self.temperature_input.text()
        print(a1)
        print(a2)
        print(a3)
        print(a4)
        print(a5)
        print(a6)
        
        a = regressor.predict([[a1,a2,a3,a4,a5,a6]])
        print('Predicted new output value: %s' % (a))
        try:
            predicted_yield = a
            self.output.setText(str(predicted_yield))
        except Exception as e:
            print(e)













    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">MANGO CROP YIELD PREDICTION MACHINE LEARNING</span></p></body></html>"))
        self.area.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">AREA</span></p></body></html>"))
        self.item.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">ITEM</span></p></body></html>"))
        self.year.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">YEAR</span></p></body></html>"))
        self.rainfall.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">RAIN FALL</span></p></body></html>"))
        self.pesticides.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">PESTICIDES</span></p></body></html>"))
        self.temperature.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">TEMPERATURE</span></p></body></html>"))
        self.PREDICTION.setText(_translate("MainWindow", "PREDICTION"))
        self.predicted_yield.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">PREDICTED YIELD</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
