# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yield.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
import numpy as np
from PyQt5.QtWidgets import QLineEdit
from PyQt5.QtWidgets import QLabel



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(726, 545)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 571, 41))
        self.label.setObjectName("label")
        self.area = QtWidgets.QLabel(self.centralwidget)
        self.area.setGeometry(QtCore.QRect(220, 130, 61, 21))
        self.area.setObjectName("area")
        self.area_input = QtWidgets.QLineEdit(self.centralwidget)
        self.area_input.setGeometry(QtCore.QRect(400, 130, 113, 20))
        self.area_input.setObjectName("area_input")
        self.item = QtWidgets.QLabel(self.centralwidget)
        self.item.setGeometry(QtCore.QRect(220, 170, 61, 21))
        self.item.setObjectName("item")
        self.year = QtWidgets.QLabel(self.centralwidget)
        self.year.setGeometry(QtCore.QRect(220, 220, 61, 21))
        self.year.setObjectName("year")
        self.rain_fall = QtWidgets.QLabel(self.centralwidget)
        self.rain_fall.setGeometry(QtCore.QRect(220, 270, 111, 21))
        self.rain_fall.setObjectName("rain_fall")
        self.pestisides = QtWidgets.QLabel(self.centralwidget)
        self.pestisides.setGeometry(QtCore.QRect(220, 310, 101, 21))
        self.pestisides.setObjectName("pestisides")
        self.tempreatrue = QtWidgets.QLabel(self.centralwidget)
        self.tempreatrue.setGeometry(QtCore.QRect(220, 350, 131, 21))
        self.tempreatrue.setObjectName("tempreatrue")
        self.temp_input = QtWidgets.QLineEdit(self.centralwidget)
        self.temp_input.setGeometry(QtCore.QRect(400, 350, 113, 20))
        self.temp_input.setObjectName("temp_input")
        self.pestiside_input = QtWidgets.QLineEdit(self.centralwidget)
        self.pestiside_input.setGeometry(QtCore.QRect(400, 310, 113, 20))
        self.pestiside_input.setObjectName("pestiside_input")
        self.rain_input = QtWidgets.QLineEdit(self.centralwidget)
        self.rain_input.setGeometry(QtCore.QRect(400, 270, 113, 20))
        self.rain_input.setObjectName("rain_input")
        self.year_input = QtWidgets.QLineEdit(self.centralwidget)
        self.year_input.setGeometry(QtCore.QRect(400, 220, 113, 20))
        self.year_input.setObjectName("year_input")
        self.item_input = QtWidgets.QLineEdit(self.centralwidget)
        self.item_input.setGeometry(QtCore.QRect(400, 170, 113, 20))
        self.item_input.setObjectName("item_input")
        self.SUBMIT = QtWidgets.QPushButton(self.centralwidget)
        self.SUBMIT.setGeometry(QtCore.QRect(320, 400, 131, 31))
        self.SUBMIT.setObjectName("SUBMIT")
        self.RESULT = QtWidgets.QLabel(self.centralwidget)
        self.RESULT.setGeometry(QtCore.QRect(240, 450, 121, 31))
        self.RESULT.setObjectName("RESULT")
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(390, 440, 101, 51))
        self.output.setFrameShape(QtWidgets.QFrame.Box)
        self.output.setText("")
        self.output.setObjectName("output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 726, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.SUBMIT.clicked.connect(self.prediction)


        


    def prediction(self):
        
        dataset = pd.read_csv('C:\Users\Anbazhagan R\Desktop\MANGOYIELD PREDICTION\CROP YIELD PREDICTION\NEW_YIELD.csv')
        print(dataset)
        x = dataset.iloc[:,:-1].values
        y = dataset.iloc[:,-1].values
        print(x)
        print(y)
        from sklearn.model_selection import train_test_split
        x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.20,random_state = 0)
        print("x_train=",x_train)
        print("x_test=",x_test)
        print("y_train=",y_train)
        print("y_test=",y_test)
        from sklearn.svm import SVR
        svr = SVR()
        svr.fit(x_train,y_train)
        area = self.area_input.text()
        item = self.item_input.text()
        year = self.year_input.text()
        rain = self.rain_input.text()
        pest = self.pestiside_input.text()
        temp = self.temp_input.text()
        output = svr.predict([[area,item,year,rain,pest,temp]])
        print('Predicted new output value: %s' % (output))
        RESULT = output
        str(RESULT)
        self.output.setText(RESULT)
        #output.show()

        
        



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">CROP YIELD PREDICTION USIING MACHINE LEARNING</span></p></body></html>"))
        self.area.setText(_translate("MainWindow", "AREA"))
        self.item.setText(_translate("MainWindow", "ITEM"))
        self.year.setText(_translate("MainWindow", "YEAR"))
        self.rain_fall.setText(_translate("MainWindow", "AVERAGE RAIN FALL"))
        self.pestisides.setText(_translate("MainWindow", "PESTISIDES TONES"))
        self.tempreatrue.setText(_translate("MainWindow", "AVERAGE TEMPREATURE"))
        self.SUBMIT.setText(_translate("MainWindow", "SUBMIT"))
        self.RESULT.setText(_translate("MainWindow", "PREDICTED RESULT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
